### ISSUE TITLE
Add Walk function to plan

### ISSUE THREAD

**Issue by erizocosmico** [src-d/go-mysql-server#106]
# Problem

We have many rules in the analyzer that need to gather some data from the whole tree before making any transformations. To do that, right now they make use of `TransformUp`, which creates a lot of nodes that are unnecessary, since we are not transforming anything, just gathering data.

# Solution

It would be very handy to have a `Walk` function in the plan that allowed us to traverse the plan nodes.

Why a function instead of a method? To not add more and more methods to the `Node` interface. Besides, we don't need all nodes to implement that, only the ones we care about. For example, we don't need table implementations to provide their `Walk` method. Plan nodes can only be generated by us, since we are the ones parsing.

Besides, we have the `Children` method in the `Node` interface, which makes having a per-node implementation of `Walk` irrelevant.

Ideal API would be the following:

```go
plan.Walk(node, func(sql.Node) plan.Visitor {
        // do something with the node
})
```

The callback should return a `Visitor` with perhaps custom logic for the given node or nil to stop.

Then the shortcut:

```go
plan.Inspect(node, func(sql.Node) bool {
        // do something with the node
})
```
The callback should return a boolean. If the result is `true` it will stop walking.

It should work like [go/ast#Inspect](https://golang.org/pkg/go/ast/#Inspect) and [go/ast#Walk](https://golang.org/pkg/go/ast/#Walk)

**Comment by ajnavarro** [comment]
Good idea!

This is needed for something pending right now?. If not, I would say to wait until the next version to implement it.

**Comment by erizocosmico** [comment]
It can certainly wait.
On Thu, 15 Mar 2018 at 11:44, Antonio Navarro Perez <notifications@github.com<mailto:notifications@github.com>> wrote:

Good idea!

This is needed for something pending right now?. If not, I would say to wait until the next version to implement it.
