### ISSUE TITLE
Add configuration per engine instance and per session

### ISSUE THREAD

**Issue by ajnavarro** [src-d/go-mysql-server#109]
We need a way to set configurations at the engine (or BBDD) and session levels. This configuration should be of two types, one specific to configure parameters on go-mysql-server (log level, number of rows to return per batch on a connection) or specific depending on the database implementation (on the gitBase case, the max size of files to return in blob table)

**Comment by erizocosmico** [comment]
Should that be in a file, environment variables, `SET` commands, ...?

**Comment by ajnavarro** [comment]
Closing as outdated. We have session and global variables implemented now.
