### ISSUE TITLE
Differences between MySQL parser and vitess parser regarding star expr

### ISSUE THREAD

**Issue by erizocosmico** [src-d/go-mysql-server#120]
This query throws a syntax error on MySQL:

```sql
SELECT bar, * FROM foo
```

In vitess, it does not.

This query throws an error on MySQL:

```sql
SELECT *, * FROM foo
 ```

In vitess, it does not.

Do we want to keep this behavior consistent with MySQL's?

**Comment by ajnavarro** [comment]
I think this is pretty cool. WDYT @smola ?

**Comment by smola** [comment]
Standard SQL behaviour would be accepting a single `*` (with no other fields) or multiple qualified stars:

BAD: `SELECT ref_name, *`

GOOD: `SELECT ref_name, commits.*`

I think MySQL also matches the standard here, but I didn't test.

So I think it would be good for us to support the later. I don't care about the former not throwing an error if its behaviour is "correct", but I don't think we have any particular interest on supporting it either.

**Comment by ajnavarro** [comment]
Right now `SELECT ref_name, * FROM refs` is already working, shall we avoid it?

**Comment by erizocosmico** [comment]
`SELECT *, ref_name FROM refs` works on MySQL.
`SELECT ref_name, * FROM refs` does not.

Additional columns are only allowed after the `*`.

**Comment by smola** [comment]
I think that promoting non-standard syntax that works inconsistently on MySQL is not the best idea. I'm inclined to say that we should just give an error.

**Comment by kuba--** [comment]
On the other hand we introduced indexes which extend just _mysql_ indexes (more like a combination of mysql and postgres). So why not to keep it as a extension/feature.

Also we may fix it by renaming the project to `go-db-server` and problem solved ;)

**Comment by smola** [comment]
As discussed offline: since we already support it, works on Vitess and partially on MySQL, we'll support it, adding tests. However, we'll NOT use this syntax in examples (we should use qualified asterisk instead).
