### ISSUE TITLE
Session souldn't be created per query

### ISSUE THREAD

**Issue by ajnavarro** [src-d/go-mysql-server#132]
Right now, we are creating a new session on every executed query. 

In my opinion, we should have a session per connection. That allows us to have some configuration attached to the actual session of the user, that can be applied to all the queries that are being executed on that connection.

One problem with that is right now a Session is also a Context. If we cancel the context, that session cannot be used again.

My proposal is to move the context outside the Session interface, in a way that you can set one on every query:

```go
type Session interface {
 SetContext(context.Context)
 GetContext()context.Context
}
```

Other solution could be separate completely the session and the context, sending both to the Nodes:

```go
type Expression interface {
[...]
	Eval(Session, Context, Row) (interface{}, error)
[...]
}
```

What do you think @erizocosmico @mcarmonaa @jfontan ?

**Comment by erizocosmico** [comment]
If you do that, you can't reuse the `Session` either because it can only hold 1 context at the same time, which is not true if you want to reuse it for multiple queries.

If the problem is the "Session" name we can change it to something else like `QueryContext` or whatever, but I think the scoping of the thing itself it's right.

**Comment by ajnavarro** [comment]
> If you do that, you can't reuse the Session either because it can only hold 1 context at the same time, which is not true if you want to reuse it for multiple queries.

Totally right, the user will be able to execute more than one query at the same time.

@erizocosmico what do you think to separate both concepts totally? having a `Session` and a `QueryContext`

**Comment by ajnavarro** [comment]
To summarize:
- `Session` at the connection level. It can store specific configuration for that session that could override default parameters. All projects that implement the engine can create his own session to store specific data or configurations for that use case
- `QueryContext` at the query level. It is in charge of canceling the query. All projects that implement the engine can create his own context implementation to store specific data.

**Comment by ajnavarro** [comment]
If I understood correctly, you will create an instance of `WhateverWeNameIt` per query, with a new context, and with the actual instantiated session for the user, right?

**Comment by erizocosmico** [comment]
Yep

**Comment by ajnavarro** [comment]
then, `WhateverYouNameIt` can be `QueryContext`, and the Node interfaces will be something like:

```go
type Expression interface {
[...]
	Eval(QueryContext, Row) (interface{}, error)
[...]
}
```

**Comment by erizocosmico** [comment]
yup
