### ISSUE TITLE
Array type

### ISSUE THREAD

**Issue by ajnavarro** [src-d/go-mysql-server#134]
Implement array type.

**Comment by erizocosmico** [comment]
I think we should have a meeting about how to implement this because MySQL does not have a proper array type (it's just JSON) and thus it won't have real support for arrays over the wire. As long as it leaves go-mysql-server land it will stop being a proper array.

**Comment by ajnavarro** [comment]
As a proposal, we can have an internal array type to have an easy way to manage the data internally. 

This type can be exposed to the outside as a JSON type.

**Comment by erizocosmico** [comment]
Yep, that sounds good.

**Comment by erizocosmico** [comment]
We'd need to merge #64 first (or start from there), it changes an interface of `sql.Type` that we also need in here.
