### ISSUE TITLE
Support arithmetic operators

### ISSUE THREAD

**Issue by ajnavarro** [src-d/go-mysql-server#142]
This query: `SELECT a+b*2+c*3+d*4+e*5, (a+b+c+d+e)/5 FROM t1 ORDER BY 1,2` throws the next error:

```
Received unexpected error:
        			            	unsupported syntax: &sqlparser.BinaryExpr{Operator:"+", Left:(*sqlparser.BinaryExpr)(0xc4203d41e0), Right:(*sqlparser.BinaryExpr)(0xc4203d4210)}
gopkg.in/src-d/go-mysql-server.v0/sql/parse.exprToExpression
        			            		/home/antonio/work/src/gopkg.in/src-d/go-mysql-server.v0/sql/parse/parse.go:459
        			            	gopkg.in/src-d/go-mysql-server.v0/sql/parse.selectExprToExpression
        			            		/home/antonio/work/src/gopkg.in/src-d/go-mysql-server.v0/sql/parse/parse.go:688
        			            	gopkg.in/src-d/go-mysql-server.v0/sql/parse.selectExprsToExpressions
        			            		/home/antonio/work/src/gopkg.in/src-d/go-mysql-server.v0/sql/parse/parse.go:445
        			            	gopkg.in/src-d/go-mysql-server.v0/sql/parse.selectToProjectOrGroupBy
        			            		/home/antonio/work/src/gopkg.in/src-d/go-mysql-server.v0/sql/parse/parse.go:415
        			            	gopkg.in/src-d/go-mysql-server.v0/sql/parse.convertSelect
        			            		/home/antonio/work/src/gopkg.in/src-d/go-mysql-server.v0/sql/parse/parse.go:99
        			            	gopkg.in/src-d/go-mysql-server.v0/sql/parse.convert
        			            		/home/antonio/work/src/gopkg.in/src-d/go-mysql-server.v0/sql/parse/parse.go:56
        			            	gopkg.in/src-d/go-mysql-server.v0/sql/parse.Parse
        			            		/home/antonio/work/src/gopkg.in/src-d/go-mysql-server.v0/sql/parse/parse.go:46
        			            	gopkg.in/src-d/go-mysql-server%2ev0.(*Engine).Query
        			            		/home/antonio/work/src/gopkg.in/src-d/go-mysql-server.v0/engine.go:30
```

**Comment by erizocosmico** [comment]
No, we don’t have arithmetic operators
On Mon, 2 Apr 2018 at 13:13, Antonio Navarro Perez <notifications@github.com<mailto:notifications@github.com>> wrote:

This query: SELECT a+b*2+c*3+d*4+e*5, (a+b+c+d+e)/5 FROM t1 ORDER BY 1,2 throws the next error:

Received unexpected error:
                                                unsupported syntax: &sqlparser.BinaryExpr{Operator:"+", Left:(*sqlparser.BinaryExpr)(0xc4203d41e0), Right:(*sqlparser.BinaryExpr)(0xc4203d4210)}
gopkg.in/src-d/go-mysql-server.v0/sql/parse.exprToExpression<http://gopkg.in/src-d/go-mysql-server.v0/sql/parse.exprToExpression>
                                                        /home/antonio/work/src/gopkg.in/src-d/go-mysql-server.v0/sql/parse/parse.go:459<http://gopkg.in/src-d/go-mysql-server.v0/sql/parse/parse.go:459>
                                                gopkg.in/src-d/go-mysql-server.v0/sql/parse.selectExprToExpression<http://gopkg.in/src-d/go-mysql-server.v0/sql/parse.selectExprToExpression>
                                                        /home/antonio/work/src/gopkg.in/src-d/go-mysql-server.v0/sql/parse/parse.go:688<http://gopkg.in/src-d/go-mysql-server.v0/sql/parse/parse.go:688>
                                                gopkg.in/src-d/go-mysql-server.v0/sql/parse.selectExprsToExpressions<http://gopkg.in/src-d/go-mysql-server.v0/sql/parse.selectExprsToExpressions>
                                                        /home/antonio/work/src/gopkg.in/src-d/go-mysql-server.v0/sql/parse/parse.go:445<http://gopkg.in/src-d/go-mysql-server.v0/sql/parse/parse.go:445>
                                                gopkg.in/src-d/go-mysql-server.v0/sql/parse.selectToProjectOrGroupBy<http://gopkg.in/src-d/go-mysql-server.v0/sql/parse.selectToProjectOrGroupBy>
                                                        /home/antonio/work/src/gopkg.in/src-d/go-mysql-server.v0/sql/parse/parse.go:415<http://gopkg.in/src-d/go-mysql-server.v0/sql/parse/parse.go:415>
                                                gopkg.in/src-d/go-mysql-server.v0/sql/parse.convertSelect<http://gopkg.in/src-d/go-mysql-server.v0/sql/parse.convertSelect>
                                                        /home/antonio/work/src/gopkg.in/src-d/go-mysql-server.v0/sql/parse/parse.go:99<http://gopkg.in/src-d/go-mysql-server.v0/sql/parse/parse.go:99>
                                                gopkg.in/src-d/go-mysql-server.v0/sql/parse.convert<http://gopkg.in/src-d/go-mysql-server.v0/sql/parse.convert>
                                                        /home/antonio/work/src/gopkg.in/src-d/go-mysql-server.v0/sql/parse/parse.go:56<http://gopkg.in/src-d/go-mysql-server.v0/sql/parse/parse.go:56>
                                                gopkg.in/src-d/go-mysql-server.v0/sql/parse.Parse<http://gopkg.in/src-d/go-mysql-server.v0/sql/parse.Parse>
                                                        /home/antonio/work/src/gopkg.in/src-d/go-mysql-server.v0/sql/parse/parse.go:46<http://gopkg.in/src-d/go-mysql-server.v0/sql/parse/parse.go:46>
                                                gopkg.in/src-d/go-mysql-server%2ev0.(*Engine).Query<http://gopkg.in/src-d/go-mysql-server%2ev0.(*Engine).Query>
                                                        /home/antonio/work/src/gopkg.in/src-d/go-mysql-server.v0/engine.go:30<http://gopkg.in/src-d/go-mysql-server.v0/engine.go:30>


This query should be supported on the current version.

**Comment by jfontan** [comment]
These are the operators that should be supported: `+`, `-`, `*`, `/` and `MOD`.

**Comment by kuba--** [comment]
Progress of this task you can track here: https://github.com/kuba--/go-mysql-server/tree/support-arithmetic-operators/142

**Comment by kuba--** [comment]
Because it was pretty straightforward I've just added all missed binary operations:
```
// BinaryExpr.Operator
const (
	BitAndStr     = "&"
	BitOrStr      = "|"
	BitXorStr     = "^"
	PlusStr       = "+"
	MinusStr      = "-"
	MultStr       = "*"
	DivStr        = "/"
	IntDivStr     = "div"
	ModStr        = "%"
	ShiftLeftStr  = "<<"
	ShiftRightStr = ">>"
)
```
