### ISSUE TITLE
Some changes to opentracing reported metrics

### ISSUE THREAD

**Issue by ajnavarro** [src-d/go-mysql-server#151]
To improve the use of opentracing, we should do some minor changes:

- Tags should only be used with data that can be used to filter between operations (per example, on `analyze` operation, we can add a tag with the output of `IsResolved` of the plan). Right now the `query` is set on a tag, move it to a `span.Log()`

- On `analyze` and `analyze_once` add a log with the plan of the node that is being processed.

- Be able to use the default jaeger [environment variables](https://github.com/jaegertracing/jaeger-client-go#environment-variables) instead of custom configuration. To do that, there is a tracer constructor on jaeger `config` package.

- Remove spans from `Merge` and `Update` aggregation methods, they are really verbose and say almost nothing, and add the span to `Eval`.

- Right now, we cannot follow the entire trace of a query because it is splitted into several parts with no relations between them; `parse`, `analyze` and the execution of the query itself. We must be able to trace at query level. 

- The tracer name must be configurable, not hardcoded to `go-mysql-server` (this can be done using `JAEGER_SERVICE_NAME`)

**Comment by ajnavarro** [comment]
What do you think about that @src-d/data-retrieval @smola ?

**Comment by smola** [comment]
@ajnavarro Sounds good. I think the most important part is that we can trace the execution phase. If we were able to track only execution (with a payload with the plan), that would be great. If other phases are there, that's ok.

**Comment by mcuadros** [comment]
I will need to see in real-life, but at the end whatever is useful for you guys.
