### ISSUE TITLE
Register a DUAL table by default

### ISSUE THREAD

**Issue by smola** [src-d/go-mysql-server#153]
The [DUAL table](https://en.wikipedia.org/wiki/DUAL_table) present [in MySQL](https://dev.mysql.com/doc/refman/5.7/en/select.html) is often used by 3rd party tools, connection pools, etc.

Registering it by default should help us to improve compatibility our of the box. It could be implemented easily with a `mem.Table`.

**Comment by ajnavarro** [comment]
This table is a little bit special, it shouldn't appear when you execute show tables, so maybe we need to add a new method to `Table` node to know if the table is hidden or not.

**Comment by smola** [comment]
@ajnavarro Maybe we don't care if it appears in `SHOW TABLES` initially?
