### ISSUE TITLE
Implement Index rule for equalities (Index.Get(...))

### ISSUE THREAD

**Issue by ajnavarro** [src-d/go-mysql-server#176]

**Comment by erizocosmico** [comment]
Since I didn't see the other task, should this cover expressions as well or just indexed columns equaled to something? Also, for this to actually be implemented it needs to be done at the same time as https://github.com/src-d/gitbase/issues/253, since you cannot do anything with the found indexes for the expressions if you can't give them to the table.

**Comment by ajnavarro** [comment]
This should cover all indexed expressions on `Equal` expressions, per example:

- `LANG(te.name) = "Go"`: if `LANG(te.name)` is indexed, we should be able to use `Index.Get("Go")` method to obtain an `IndexLookup` object. `IndexLookup` object will implement the simplest interface, containing `Values()valueIterator` method.

We can start with a first approach just using literals, and then, on a second iteration, be able to evaluate expressions to get the Literal.

**Comment by erizocosmico** [comment]
# Proposal

Create a new rule `find_indexes` (or whatever) that does the following:

- Walk the expressions of nodes that are not projections.
- For each expression that is encountered we ask the index registry if there's any index for that expression until any of them matches.
- If the matched expression is just a column, make sure is in an equality with a literal.
- Gather all indexes in order until we have the full list of usable indexes. If they can be combined left-to-right (from first to last) we do so until they can't be combined anymore. The rest are discarded. That ensures we use as many as possible but in case we can't we only use the first-most indexes.
- Push the resultant index to the corresponding table and wrap it with an `IndexableTable` node.

## Pending stuff

- Not sure what to do with multi-column indexes or how to fit them here

**Comment by ajnavarro** [comment]
Added an example of multi-column index on my previous comment. We can leave it for a second iteration.
