### ISSUE TITLE
Row's indexes are not handled properly

### ISSUE THREAD

**Issue by mcarmonaa** [src-d/go-mysql-server#180]
For queries involving `CROSS JOIN` and `INNER JOIN` the column resolution is done right for the resulting schema, but is not handle correctly for intermediate phases of the execution.

For example, for a query like:
```
SELECT * FROM repositories r,
		commits c INNER JOIN tree_entries te
			ON c.tree_hash = te.tree_hash
```

with the following plan:
```
CrossJoin
 ├─ TableAlias(r)
 │   └─ PushdownProjectionAndFiltersTable
 │       ├─ Columns(repositories.id)
 │       ├─ Filters()
 │       └─ Table(repositories)
 │           └─ Column(id, TEXT, nullable=false)
 └─ InnerJoin(commits.tree_hash = tree_entries.tree_hash)
     ├─ TableAlias(c)
     │   └─ PushdownProjectionAndFiltersTable
     │       ├─ Columns(commits.hash, commits.author_name, commits.author_email, commits.author_when, commits.committer_name, commits.committer_email, commits.committer_when, commits.message, commits.tree_hash, commits.parents)
     │       ├─ Filters()
     │       └─ Table(commits)
     │           ├─ Column(hash, TEXT, nullable=false)
     │           ├─ Column(author_name, TEXT, nullable=false)
     │           ├─ Column(author_email, TEXT, nullable=false)
     │           ├─ Column(author_when, TIMESTAMP, nullable=false)
     │           ├─ Column(committer_name, TEXT, nullable=false)
     │           ├─ Column(committer_email, TEXT, nullable=false)
     │           ├─ Column(committer_when, TIMESTAMP, nullable=false)
     │           ├─ Column(message, TEXT, nullable=false)
     │           ├─ Column(tree_hash, TEXT, nullable=false)
     │           └─ Column(parents, JSON, nullable=false)
     └─ TableAlias(te)
         └─ PushdownProjectionAndFiltersTable
             ├─ Columns(tree_entries.tree_hash, tree_entries.entry_hash, tree_entries.mode, tree_entries.name)
             ├─ Filters()
             └─ Table(tree_entries)
                 ├─ Column(tree_hash, TEXT, nullable=false)
                 ├─ Column(entry_hash, TEXT, nullable=false)
                 ├─ Column(mode, TEXT, nullable=false)
                 └─ Column(name, TEXT, nullable=false)

```

The resulting schema is:
```
0: id
1: hash
2: author_name
3: author_email
4: author_when
5: committer_name
6: committer_email
7: committer_when
8: message
9: tree_hash
10: parents
11: tree_hash
12: entry_hash
13: mode
14: name
```
When the `resolveColumns` rule in the `analyzer` changes the `GetField` expressions in the plan, it set the row's index where the value for each field of the schema should be placed in a `sql.Row` referred to this schema.

However, for the query example, when the rows are evaluated in the inner join iterator, the value for first field `id` that comes from the `repository` table, isn't present in the `sql.Row` at this point because the cross join hasn't produced yet.

 Then, the condition for the inner join that use the fields `tree_hash` will take the indexes set in the `GetField` expression 9 and 11, but actually the the `sql.Row` in this iterator only has 14 values, not 15, and the correct fields are in the positions 8 and 10.

In this example, when you try to iterate to get the rows it panics because of the wrong selected values to perform the join have different types and can't be compared. In other cases it could be panic with an `index out of bounds`, or in the worst case, it could not panic and make the inner join on wrong fields.

**Comment by mcarmonaa** [comment]
As talked with @ajnavarro  in real life, for the moment we can add rule to find inner joins and set the `GetField` from the child's expression to the an index referring the resulting schema of the inner join.

In the future we should avoid to have global row's index and have each node that generates new  `sql.Row`s getting values indexing with its own schema.

**Comment by mcarmonaa** [comment]
In this #181 PR is implemented the solution to fix it for all the cases.

Since `resolveColumns` were setting indexes for `GetField` expression in a global way based in the final schema of the query, I removed that logic and added a new rule `resolveGetFieldIndexes` resolving these indexes using values regarding with the schema of the node that contains the expression.

I think the best way to fix is through a rule in the analyzer because from the plan you can get the correct schema for each expression and set the correct value. In runtime you should know this when an expression is evaluated to choose the correct indexes for the fields in the `sql.Row`, an there's no way for an expression to get a reference to the `sql.Node` which owns it. Also, in runtime the logic to retrieve the correct indexes will be executed for each row in each expression evaluation.

**Comment by erizocosmico** [comment]
Isn't this done in #181? Should we move this to PR instead?

**Comment by mcarmonaa** [comment]
Yes, It's done in #181
