### ISSUE TITLE
Make `sql.Expression` interface de/serializable...

### ISSUE THREAD

**Issue by kuba--** [src-d/go-mysql-server#194]
In `IndexDriver` implementation, we have to deal with `sql.Expression` interface (serialize it in `Create` and deserialize in `Load`). Deserialize an interface in *go* is not really possible, so here are couple of proposals how to make `sql.Expression` type more flexible to work with:
- Add *(Un)Marshal* functions, so everyone who implements the interface will have to know how to serialize it to `[]byte` and how to deserialize it from `[]byte`.
- Create `ExpressionRegistry` and all concrete implementations will have to register `Expression` type with unique name in global registry. And downstream this information to components like `IndexDriver` where information about concrete implementation is needed.
- Attach some kind of _hash reference_ to every `sql.Expression` implementation and in components like `IndexDriver`, `sql.Index`, ... use only _hash reference_ strings instead of _expression objects_.

Right now `sql.Expression` interface is:
```go

// Expression is a combination of one or more SQL expressions.
type Expression interface {
	Resolvable
	fmt.Stringer
	// Type returns the expression type.
	Type() Type
	// IsNullable returns whether the expression can be null.
	IsNullable() bool
	// Eval evaluates the given row and returns a result.
	Eval(*Context, Row) (interface{}, error)
	// TransformUp transforms the expression and all its children with the
	// given transform function.
	TransformUp(TransformExprFunc) (Expression, error)
	// Children returns the children expressions of this expression.
	Children() []Expression
}
```

For instance in _Pilosa driver_ apart from (de)serialize it in `Load, Create` we also iterate through all expression in `Save` (because we treat them as column names) and map them to _Pilosa frame names_. To make it possible we just convert them to `string` just calling `String()` function:
```go
for i, e := range idx.Expressions() {
		encodedFrameName := encode(e.String())
		frames[i], err = index.Frame(encodedFrameName)
	...
```

So for _index driver_ it would be better if expressions were just a slice of strings.
This task should be accomplished before we start continue working on: https://github.com/src-d/go-mysql-server/issues/174

**Comment by ajnavarro** [comment]
Should we abstract all this logic from Index implementations, and just send ExpressionsIDs?

Per example:

```go
type Index interface {
...
Expressions() []Expression
...
}
```

Should be:
```go
type ExpressionID string

type Index interface {
...
ExpressionIDs() []ExpressionID
...
}
```

And in the case of `IndexDriver` interface, we can do the same.

All the encode logic can be on top of the Index implementation, and generic. WDYT?

**Comment by kuba--** [comment]
I'm OK with any type which can be easily _(de)serialized_ and mapped to `string` and/or `[]byte`.

**Comment by kuba--** [comment]
Maybe `encoding/gob` can help in some way, but it requires to register a type. Here I've played a little bit with deserialising interface:
https://play.golang.org/p/bVT60uj3aXw

**Comment by kuba--** [comment]
PR: https://github.com/src-d/go-mysql-server/pull/200
