### ISSUE TITLE
Document motivation and scope of the project

### ISSUE THREAD

**Issue by smola** [src-d/go-mysql-server#203]
We should be clear about motivation and scope of the project. It is important for people to understand:

- What are project goals? (e.g. creating a SQL interface to arbitrary storage backends)
- What are the intended use cases?
- What are NOT project goals? (e.g. creating a SQL database)

As the project gets more attention, this becomes important to avoid confusing users (e.g. https://github.com/src-d/go-mysql-server/issues/198).

**Comment by smola** [comment]
Note that the current description of the project is actually misleading, and users might thing that by "MySQL server" we mean a drop-in replacement or something comparable at all in terms of functionality.

**Comment by ajnavarro** [comment]
Addressed part of the issue here: https://github.com/src-d/go-mysql-server/pull/207

**Comment by erizocosmico** [comment]
Perhaps the project should be `go-mysql-engine` instead? That would be less confusing.

**Comment by ajnavarro** [comment]
Reopen to keep the discussion about the project name @smola

**Comment by smola** [comment]
I think it's ok to keep it at the moment and avoid further breakage, but we could discuss before v1.

**Comment by erizocosmico** [comment]
Should we move this out of todo or add the blocked label, since this has no actionable tasks right now?

**Comment by smola** [comment]
@erizocosmico @ajnavarro Maybe you can just close it, the original issue is solved (documentation in README).
