### ISSUE TITLE
analyzer: Check rule that try merge compatible indexes.

### ISSUE THREAD

**Issue by ajnavarro** [src-d/go-mysql-server#213]
We need to check the actual rule that makes use of SetOperations and Mergeable Lookup interfaces.

This rule will be in charge of checking all the obtained indexes and try to merge them all together.

If not all the indexes are mergeable, use the most merged Index Lookup and discard the rest.

**Comment by erizocosmico** [comment]
That's already implemented https://github.com/src-d/go-mysql-server/blob/master/sql/analyzer/rules.go#L1099-L1258

**Comment by erizocosmico** [comment]
Depends on #212

**Comment by erizocosmico** [comment]
Blocked until #212 is done

**Comment by erizocosmico** [comment]
This is not blocked anymore
