### ISSUE TITLE
Create rule to move filters from Join conditions to where clauses

### ISSUE THREAD

**Issue by ajnavarro** [src-d/go-mysql-server#235]

**Comment by erizocosmico** [comment]
Only the ones that do not involve both tables, right?

For example, in`ON t1.foo = t2.bar AND t1.baz = 'foo'` only `t1.baz = 'foo'` would be pushed down, right?

**Comment by ajnavarro** [comment]
Right, when one of the sides are not involving the two tables, it should be moved to WHERE expressions.
