### ISSUE TITLE
Create Pilosa Index - Performance Improvements

### ISSUE THREAD

**Issue by kuba--** [src-d/go-mysql-server#241]
So far creating an index is really slow and consumes lot of resources. Here are some numbers:
- I've created a _language index_ based on *4 our repositories*: baremetal, borges, envconfig, gcfg, gitbase.
- 1613800 rows saved
- It took ~ *2 hours*
- pilosa-mapping.db file size ~ *824 MB*

**Comment by ajnavarro** [comment]
Do you know where is spent all the time?

**Comment by kuba--** [comment]
I didn't run it with profiler (it was just reproducing https://github.com/src-d/go-mysql-server/issues/238), so I'm guessing IO (mapping + pilosa http). And now as a part of my fix (https://github.com/src-d/go-mysql-server/pull/240) we'll have an extra strep where we need to `Eval` expressions.
If it's a Pilosa-Bolt IO case maybe we can try Bulk/Batch requests as first step of improvement.

**Comment by erizocosmico** [comment]
This depends on the work @jfontan is doing adding tracing support for indexes, right?

**Comment by ajnavarro** [comment]
closed by: https://github.com/src-d/go-mysql-server/pull/250
