### ISSUE TITLE
Sync create index queries

### ISSUE THREAD

**Issue by erizocosmico** [src-d/go-mysql-server#271]
There are some cases, such as tests or gitbase regression tests where you don't want to create the indexes in the background because you need them to be created before you start doing queries.

Do this manually requires a lot of knowledge about the insides and they are susceptible to change. By optionally letting the user decide if they should be sync or async we can abstract all this away and just use a query to create them.

It could be some config or environment variable.

WDYT? @ajnavarro

**Comment by jfontan** [comment]
Other way it can be done is checking logs but I also think it's also better to have a sync version. It's also good to get how much time it took to create the index.
