### ISSUE TITLE
Partitions: Rules to apply Exchange operator into query trees

### ISSUE THREAD

**Issue by ajnavarro** [src-d/go-mysql-server#313]
The following actions should be implemented as analyzer rules to be able to parallelize queries:
- If parallelization is > 1, we can introduce an Exchange node, if not, the rule is doing nothing.

- Exchange nodes should be added on top of much nodes as possible.

- We stop adding nodes inside Exchange node when we found a binary node or the last node with no parents. We must also stop adding nodes inside Exchange node if we find an Aggregation. In the future, we can parallelize that kind of nodes too.

- We cannot add Exchange nodes on top of other Exchange nodes, but we can have several Exchange nodes on siblings (see example graph).

- Exchange nodes must finish always in a table.

**Comment by erizocosmico** [comment]
Depends on #312

**Comment by erizocosmico** [comment]
@ajnavarro parallelism is configurable or will we use a hardcoded value?

**Comment by ajnavarro** [comment]
@erizocosmico Configurable: https://docs.google.com/document/d/1Z-5twQzCMb2CvC0AKzDkCM0VxLPC4sevKe4MD121Wvs/edit#heading=h.s5t1byc1rvtr
