### ISSUE TITLE
Unable to connect to _example/main.go mem server using Java JDBC driver 

### ISSUE THREAD

**Issue by vireshas** [src-d/go-mysql-server#319]
I am trying to connect to the default mem server using the Java JDBC driver and I get the following error.

`Exception in thread "main" org.skife.jdbi.v2.exceptions.UnableToObtainConnectionException: java.sql.SQLException: unknown error: unsupported feature: SHOW variables`

I looked at the code and found that `show variables` is not yet supported. Wanted to know if there is way to make this work without implementing the `show variables` in go-mysql-server.

```
package com.mycompany.app;

import java.util.List;
import java.util.Map;
import org.skife.jdbi.v2.DBI;
import org.skife.jdbi.v2.Handle;
import org.skife.jdbi.v2.Query;
import com.mysql.jdbc.Driver;

public class App {

    public static void main(String[] args) {

        try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }

        Handle handle = null;
        try {
            DBI dbi = new DBI("jdbc:mysql://localhost:3306/test",
                              "username",
                              "password");

            String sql = "SELECT * FROM table";

            handle = dbi.open();

            Query<Map<String, Object>> q = handle.createQuery(sql);
            List<Map<String, Object>> l = q.list();

            for (Map<String, Object> m : l) {
                System.out.println(m);
            }

        } finally {
            if (handle != null) {
                handle.close();
            }
        }
    }
}

```

```
Exception in thread "main" org.skife.jdbi.v2.exceptions.UnableToObtainConnectionException: java.sql.SQLException: unknown error: unsupported feature: SHOW variables
	at org.skife.jdbi.v2.DBI.open(DBI.java:229)
	at com.mycompany.app.App.main(App.java:30)
Caused by: java.sql.SQLException: unknown error: unsupported feature: SHOW variables
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:996)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3887)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3823)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2526)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1446)
	at com.mysql.jdbc.ConnectionImpl.loadServerVariables(ConnectionImpl.java:3828)
	at com.mysql.jdbc.ConnectionImpl.initializePropsFromServer(ConnectionImpl.java:3268)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2278)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2064)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:790)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:395)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:325)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:215)
	at org.skife.jdbi.v2.DBI$3.openConnection(DBI.java:139)
	at org.skife.jdbi.v2.DBI.open(DBI.java:211)
	... 1 more
```

**Comment by erizocosmico** [comment]
Hi! thanks for reporting.

Right now, there is no support on go-mysql-server for `SHOW`, and it can't be fixed without doing it there.

Making gitbase work with other external tools is in the roadmap, though, so we will definitely look into that.

**Comment by smola** [comment]
You might want to try with a different JDBC driver (e.g. MariaDB's). We didn't try for Java yet, but in the case of Python, official driver tried to do more obscure things while alternative driver (pymysql) works after disabling autocommit.

**Comment by ajnavarro** [comment]
I made JDBC work using the MariaDB client driver and adding that lines on `Engine.Query()` method. Maybe as a temporal workaround this work for you:

```go
if query == "SELECT @@max_allowed_packet,@@system_time_zone,@@time_zone,@@auto_increment_increment" {
        return sql.Schema{
                &sql.Column{Name: "a", Type: sql.Int32},
                &sql.Column{Name: "b", Type: sql.Text},
                &sql.Column{Name: "c", Type: sql.Text},
                &sql.Column{Name: "d", Type: sql.Int32},
            },
            sql.RowsToRowIter(sql.NewRow(1000, "UTC", "UTC", 1)), nil
    }

    if query == "set autocommit=1, sql_mode = concat(@@sql_mode,',STRICT_TRANS_TABLES')" {
        return sql.Schema{}, sql.RowsToRowIter(), nil
    }
```

**Comment by vireshas** [comment]
Thank you for the pointers!

I'll try it out and update my progress here.

**Comment by ajnavarro** [comment]
Hey @vireshas , we did some improvements on JDBC compatibility using MariaDB driver, you can have a look on it to see if it is working for your use case.

**Comment by vireshas** [comment]
@ajnavarro Thank you for the update. I did run my older code and could see some exceptions. 
Will try and debug tomorrow.

P.S. Being a Java shop we are also evaluating Calcite.

**Comment by bzz** [comment]
Just stumbled up on this with Python - without this, one can not use SQLAlchemy to read gitbase response to Pandas DataFrame

```
$ pip3 install pandas sqlalchemy PyMySQL
```
and
```python
import pandas as pd
import sqlalchemy

engine = sqlalchemy.create_engine('mysql+pymysql://root@127.0.0.1:3306/mysql')
example_df = pd.read_sql_table("repositories", engine)
```

results in 
```
InternalError: (pymysql.err.InternalError) (1105, 'unknown error: unsupported feature: SHOW variables') [SQL: "SHOW VARIABLES LIKE 'sql_mode'"] (Background on this error at: http://sqlalche.me/e/2j85)
```

as SQLAlchemy seems to use this to [detect sql mode](https://github.com/zzzeek/sqlalchemy/blob/master/lib/sqlalchemy/dialects/mysql/base.py#L2395).

Is there any known workaround in order to be able to overcome this?
Thanks in advance!

**Comment by bzz** [comment]
Originally I was testing on gitbase 0.17.1 \w old version of go-mysql-server 

With the latest release candidate using 8cb8028a413e4edf66c4b57bc3eb570950d7bcfb support for `SHOW VARIABLES` was added and [documented](https://github.com/src-d/go-mysql-server/commit/053c8dd0f39cbd1f71948d954b6f9e36d2e5fe62)

@vireshas could you verify if this solves the issue for you?

Will moving further discussion \ feature requests needed for SQLAlchemy support to another issue, similar to what was done for [Tableau](https://github.com/src-d/go-mysql-server/issues?utf8=%E2%9C%93&q=is%3Aissue+Tableau).

**Comment by smola** [comment]
@bzz Could you file a separate issue for SQLAlchemy?

**Comment by vireshas** [comment]
@bzz, I got it to a working state after I made some changes to `go-mysql-server` as suggested by @ajnavarro in his first reply.

I never had a problem with python+pymysql as I wasn't using SQLAlchemy. 

My use-cases were quite different as well. One of the teams stopped updating a MySql DB. To avoid code changes in multiple repos, I had to pull the data from various sources and retain the format & protocal.

**Comment by ajnavarro** [comment]
@vireshas I will close this as fixed, If you have still any problem, don't hesitate to reopen it.

Also, we did a really huge effort the last month to make go-mysql-server compatible with a lot of clients languages, check: https://github.com/src-d/go-mysql-server/blob/master/SUPPORTED_CLIENTS.md. 

So If you want you can also try updating go-mysql-server to the latest version and drop the workaround I provided.

**Comment by bzz** [comment]
> @bzz Could you file a separate issue for SQLAlchemy?

@smola SQLAlchemy support issues created and linked above
