### ISSUE TITLE
performance issue - indexed queries are much slower than non indexed

### ISSUE THREAD

**Issue by kuba--** [src-d/go-mysql-server#324]
Non indexed queries like:
```
SELECT count(*) FROM commits WHERE  commit_author_email='existing email';

SELECT count(*) FROM commits WHERE  NOT (commit_author_email='existing email');
```
return in ~ 1sec. (tested on gitbase repo where commits table has 580 rows) 180 and 394 rows.

After we create an index (for both drivers):
```
CREATE INDEX email_idx ON commits USING pilosalib (commit_author_email);
```
Above queries take: ~5sec, ~10sec.

It's much slower than queries without any index.

It's not a problem of original queries with `group by` or `count`. It's also not a problem with `NOT` operator (which doesn't exist on pilosa). Pilosa and mapping are pretty fast. But because we have to iterate all the time calling `Next`it causes a performance bottleneck.
Pilosa can return (even for simulated NOT operator) 500 columns in couple ms.

**Comment by kuba--** [comment]
Full scans are super slow with indexes, e.g.:
674 rows, no indexes: 1.2s.
674 rows, pilosalib index: 15s. (because we have to retrieve data from mapping for each row).
If we memorize it first we can go down to 170s. for indexed full scan.

I'll consider to store locations pilosa column attributes.

**Comment by ajnavarro** [comment]
Ideally, if the Index result count is almost the same as the total of elements on the table, use the index is useless. Maybe we should get first the number of results that that index is going to return. If the amount of elements is almost the total amount of elements on the indexed tables, it's better to do a full scan and filter a few elements. WDYT?

**Comment by kuba--** [comment]
I'm trying queries like this one: 
`SELECT count(*) FROM commits WHERE commit_author_email!='kuba@sourced.tech';`
(count doesn't matter here).
For indexes the problem is iterator. Every time when you call `Next` to goes to the mapping.

**Comment by kuba--** [comment]
btw. we always group everything first, then aggregate.
```go
func (i *groupByIter) computeRows() error {
	rows := []sql.Row{}
	for n := 0; ; n++ {

		childRow, err := i.childIter.Next() // <--------------

		if err == io.EOF {
			break
		}
		if err != nil {
			return err
		}
		rows = append(rows, childRow) // <----------
	}

	rows, err := groupBy(i.ctx, rows, i.p.Aggregate, i.p.Grouping)
	if err != nil {
		return err
	}

	i.rows = rows
	return nil
}
```

**Comment by kuba--** [comment]
OK, I deeply dived into the problem, where is a bottleneck. My first thought was index mapping (because for each row we have to hit boltdb), but profiling showed it wasn't the case. The second assumption was related to lot of copy operation on `[]byte`, but after converting debug code to `unsafe.Pointer`s to avoid coping I didn't notice much difference.
After walking through the stack trace it turns out that the most time we spend in gitbase's `commitsIndexIter.Next()` doing _decoding_.
For non-indexed full scan queries we _don't_ call `commitsIndexIter.Next`, but for indexed we do.

In `commitsIndexIter.Next` function we call 3 operations:
- `index.Next()`
- ` decodeIndexKey(data, &key)`
- `decoder.decode(key.Repository,plumbing.NewHash(key.Packfile), Offset, plumbing.NewHash(key.Hash))`

First 2 functions are pretty fast:
```
index.Next():	 318ns
decodeIndexKey(data, &key): 24.48µs
```

but the last one (`decode`) takes 20-30ms per row.
what proofs my math where to get ~670 rows takes ~ 15s.!
Where non-indexed full scan gives us the same amount of rows in 1.2s.

**Comment by kuba--** [comment]
It turned out that it was a issue in gitbase decoder, not in mysql engine.
PR: https://github.com/src-d/gitbase/pull/419
