### ISSUE TITLE
sql.IndexLookup should be able to return the IDs of all indexes involved

### ISSUE THREAD

**Issue by erizocosmico** [src-d/go-mysql-server#333]
If we could return the IDs of all the indexes involved in an index lookup we might be able to present the user better information in describe queries. After assigning indexes we lose the ability to recall which index we used, so we only have the IndexLookups.

**Comment by ajnavarro** [comment]
Could you provide an example of what do you want to accomplish with that change please?

**Comment by erizocosmico** [comment]
`DESCRIBE` queries for squashed tables (and regular tables) in gitbase, for example, could output the IDs of the indexes being used, which is nice for debugging, since there's no way of telling if an index is being used or not right now other than manually debugging.

**Comment by ajnavarro** [comment]
oh, I see. Per example, you want to print on the `IndexableTable` node something like:

```
IndexableTable
	Indexes:
		commit_author_name_idx
		commit_author_email_idx
[...]
```

**Comment by erizocosmico** [comment]
Exactly
