### ISSUE TITLE
Proposal: add build flag to be able to use REGEXP statement with Oniguruma

### ISSUE THREAD

**Issue by ajnavarro** [src-d/go-mysql-server#341]
Go regular expressions are not as fast as they should. To make REGEXP statement faster, we can add the possibility of compile with Oniguruma regular expressions instead of Go ones.

Similar case here: https://github.com/src-d/enry/pull/156

**Comment by jfontan** [comment]
Done in gitbase: src-d/gitbase#452

**Comment by erizocosmico** [comment]
Take into account that https://github.com/moovweb/rubex master is not usable and branch go1 should be used
