### ISSUE TITLE
Proposal: Specify function arity instead of using reflection

### ISSUE THREAD

**Issue by erizocosmico** [src-d/go-mysql-server#37]
## Current state

Right now, we pass a `interface{}` as the UDF, which then is inspected and called using `reflect`.

## Proposal

Instead, I propose to have fixed arity specified by the user.

Benefits of this:
- does not use reflection, so more maintainable code
- just looking at the registry you can see the arity of the function
- does not allow random signatures, so it's more type-safe

The implementation would look like the following:

```go
type Function interface {
        Arity() int
}

type Function1 func(sql.Expression) sql.Expression
type Function2 func(sql.Expression, sql.Expression) sql.Expression)
// ...
type FunctionN func(sql.Expression, sql.Expression, sql.Expression, sql.Expression) sql.Expression)

func (Function1) Arity() int { return 1 }
func (Function2) Arity() int { return 2 }
// ...
func (FunctionN) Arity() int { return n }

// Call could be converted to Call(...sql.Expression) 
func Call(fn Function, exprs ...sql.Expression) (sql.Expression, error) {
        if fn.Arity() != len(exprs) { /* throw error */ }
        switch fn := fn.(type) {
        case Function1: fn(exprs[0])
        // ...
        }
}
```

Then in the registry:

```go
var Functions = map[string]Function{
        "func": Function1(NewMyFunc),
}
```

**Comment by jfontan** [comment]
Why not passing an array of expressions instead of having types for each number of args? The info about the arity can be added to the registry somehow if needed or let the function return error if the arity is incorrect.

**Comment by erizocosmico** [comment]
Type-safety, basically. By doing `Function2(NewFoo)` you're forcing `NewFoo` to have a specific signature. Of course, you can only know the number of arguments is correct in eval time, but that's why `Call` returns an error if the arity does not match. By doing it in `Call`, you avoid having to validate the arity every single time inside all functions and just trust the input you received.

**Comment by ajnavarro** [comment]
I like the idea. Adding enhancement flag to go ahead.
