### ISSUE TITLE
Support for `GROUP BY` on aliased fields

### ISSUE THREAD

**Issue by campoy** [src-d/go-mysql-server#375]
This seems like a bug on the scope management for identifiers.

While this query works:
```sql
select repository_id, count(ref_name) as count
from refs
group by repository_id;
```

This one fails with the error message `column "repo" could not be found in any table in scope`:
```sql
select repository_id as repo, count(ref_name) as count
from refs
group by repo;
```

My current workaround is to use a nested query, but this is clearly a hack.
```sql
select repo, count(ref_name) as count
from (
    select repository_id as repo, ref_name
    from refs
) as t
group by repo;
```

**Comment by ajnavarro** [comment]
This should be fixed by https://github.com/src-d/go-mysql-server/pull/368

Can you try updating to latest master?

**Comment by campoy** [comment]
This issues is fixed in the latest release, when will it be deployed to dockerhub?
We need to make sure these fixes are on the gitbase image so the engine benefits from it.

**Comment by ajnavarro** [comment]
deployed as v0.17.0-rc.3 https://hub.docker.com/r/srcd/gitbase/tags/
