### ISSUE TITLE
Test 3rd party applications integration

### ISSUE THREAD

**Issue by ajnavarro** [src-d/go-mysql-server#387]
To be sure that we keep compatibility with 3rd party applications, we need to create some integration tests for that. 

- They should be executed on a separated job after unit tests.
- All supported drivers used to connect should be added as a new integration test.
- We should add on docs a new entry called `integrations` or `supported applications`.
- Add tests for the following clients (they are in priority order):
	- JDBC (MariaDB)
		- Query set that is executed by Spark (we don't need to start a spark instance for that, just send that queries over a JDBC connection)
		- Query set executed by Tableau
	- Python Mysql driver
	- pymysql Python driver
	- Go mysql driver
		- Query set that is executed by Grafana.
		- Query set executed by mysqldump (add when the mysqldump is supported, we can ignore before that).
	- MySQL Javascript driver
	- MySQL PHP driver
	- MySQL Ruby driver
	- MySQL .NET driver

**Comment by smola** [comment]
See https://github.com/src-d/go-mysql-server/issues/391

**Comment by erizocosmico** [comment]
@ajnavarro Should we do this in this repo or in another one?

**Comment by ajnavarro** [comment]
I would say to do on this repo. We need to be sure that we don't break any backward compatibility on any new functionality.

**Comment by erizocosmico** [comment]
This was done

**Comment by smola** [comment]
Just for the record:  Tableau work continues here: https://github.com/src-d/go-mysql-server/issues/468
