### ISSUE TITLE
Add support for LOWER, UPPER

### ISSUE THREAD

**Issue by smola** [src-d/go-mysql-server#390]
Add support for LOWER and UPPER:
* https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_lower
* https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_upper

**Comment by cpanato** [comment]
there any example for others? @smola

**Comment by Zarkopafilis** [comment]
I am on this.

**Comment by smola** [comment]
@Zarkopafilis @cpanato  It should be implemented as an `Expression`, see examples here:
* https://github.com/src-d/go-mysql-server/tree/master/sql/expression
* https://github.com/src-d/go-mysql-server/blob/master/sql/expression/isnull.go
* https://github.com/src-d/go-mysql-server/blob/master/sql/expression/arithmetic.go

**Comment by smola** [comment]
See similar issues:
* https://github.com/src-d/go-mysql-server/issues/389
* https://github.com/src-d/go-mysql-server/issues/392

**Comment by Zarkopafilis** [comment]
@smola After implementing the Expression interface unser /expression/blabla.go and adding the tests, as well as changing the SUPPORTED.md contents to match, do we need to register the newly created expression somewhere?

**Comment by ajnavarro** [comment]
Yes, you should add the function to `Defaults`: https://github.com/src-d/go-mysql-server/blob/5e5ad98fe4b29ae75189e63762f02599b8bc0188/sql/expression/function/registry.go#L9
