### ISSUE TITLE
Add support for LOG, LOG2, LOG10, LN

### ISSUE THREAD

**Issue by smola** [src-d/go-mysql-server#392]
* https://dev.mysql.com/doc/refman/8.0/en/mathematical-functions.html#function_ln
* https://dev.mysql.com/doc/refman/8.0/en/mathematical-functions.html#function_log
* https://dev.mysql.com/doc/refman/8.0/en/mathematical-functions.html#function_log10
* https://dev.mysql.com/doc/refman/8.0/en/mathematical-functions.html#function_log2

**Comment by theodesp** [comment]
I will be willing to take this

**Comment by smola** [comment]
@theodesp Sure! Feel free to ask any doubt, also check https://github.com/src-d/go-mysql-server/issues/390 for some more info.
