### ISSUE TITLE
Resolve tables with database qualifier

### ISSUE THREAD

**Issue by erizocosmico** [src-d/go-mysql-server#402]
Right now, tables can't have database qualifiers. We should be able to resolve them with database qualifiers.

We should check if columns can also be qualified with the database. If they can, they should also be handled.

See: https://github.com/src-d/gitbase/issues/361#issuecomment-427285397

**Comment by ajnavarro** [comment]
I think is a good idea. On SparkSQL they have `UnresolvedAttribute` that becomes `AttributeReference` on `ResolveReferences` rule (just if you want to have a look).

We can take advantage of this refactor and try to improve column and aliases resolution, that they are causing some problems.
