### ISSUE TITLE
Implement SHOW CREATE DATABASE

### ISSUE THREAD

**Issue by erizocosmico** [src-d/go-mysql-server#407]
Implement `SHOW CREATE DATABASE` statement.

See: https://github.com/src-d/gitbase/issues/361#issuecomment-427285397

**Comment by theodesp** [comment]
I will be willing to implement this. I would like to ask though where do we query the following Variables:

* DEFAULT CHARACTER SET
* COLLATE

As I could not find them in the source code

**Comment by erizocosmico** [comment]
We don't use charsets or collations right now, so we might want to decide on one and just return that value for now. @ajnavarro which ones should we use as defaults?
