### ISSUE TITLE
Implement SHOW VARIABLES

### ISSUE THREAD

**Issue by erizocosmico** [src-d/go-mysql-server#409]
Implement `SHOW VARIABLES` statement.

There should be some built-in values, such as `gtid_mode` and so on.

See: https://github.com/src-d/gitbase/issues/361#issuecomment-427285397

**Comment by marcosvm** [comment]
@erizocosmico I'd like to take a chance on this issue over the weekend if you still need help with it.

**Comment by erizocosmico** [comment]
@marcosvm Sure! Feel free to ask any question you may have about it.

**Comment by kuba--** [comment]
@marcosvm - If you wanna implement it over the weekend, go ahead and re-assign the task to yourself. 
On my branch I've just added simple parser and dummy iterator: https://github.com/kuba--/go-mysql-server/tree/enh-409/show-vars
So nothing advanced, so far.

**Comment by marcosvm** [comment]
@kuba-- Please go ahead, I got caught on other "stuff" and could not work on thi.
