### ISSUE TITLE
Support quoted numbers as strings

### ISSUE THREAD

**Issue by theodesp** [src-d/go-mysql-server#445]
Currently any operation that involves quoted strings fail to parse correctly. For example this works in the latest mysql server:

```
mysql> select ceil('1.2');
+-------------+
| ceil('1.2') |
+-------------+
|           2 |
+-------------+
1 row in set (0.00 sec)
```

but in this server:

```
mysql> select ceil('1.2');
+-------------+
| CEIL("1.2") |
+-------------+
|           0 |
+-------------+
1 row in set (0.00 sec)
```

**Comment by Zarkopafilis** [comment]
I get `$ mysql --host=127.0.0.1 --port=3306 -u user -ppass --default-auth=mysql_native_password test -e "SELECT CEIL("1.2");"
mysql: [Warning] Using a password on the command line interface can be insecure.
+-----------+
| CEIL(1.2) |
+-----------+
|         2 |
+-----------+`

On commit `77ee523` (latest on master)

**Comment by theodesp** [comment]
While it works for double quotes it doesn't for single ones
