### ISSUE TITLE
Inconsistent Errors using backticks

### ISSUE THREAD

**Issue by theodesp** [src-d/go-mysql-server#447]
Currently, if you use backticks in the wrong place you get a different error code. For example:

Mysql-8
---
```
mysql> select ceil(`1.2`);
ERROR 1054 (42S22): Unknown column '1.2' in 'field list'
```

go-mysql-server
---
```
mysql> select ceil (`8.88`);
ERROR 1105 (HY000): unknown error: column "8.88" could not be found in any table in scope
```

**Comment by erizocosmico** [comment]
Yeah, errors in go-mysql-server are not compatible with MySQL's. That is by design, for now.

@ajnavarro what should we do with this?

**Comment by ajnavarro** [comment]
We try to emulate MySQL behavior as much as possible. If some statement with specific parameters throws an error, we should throw an error too. But we cannot ensure that the error will be the same always.
