### ISSUE TITLE
Float results get truncated

### ISSUE THREAD

**Issue by theodesp** [src-d/go-mysql-server#450]
I'm trying to implement https://github.com/src-d/go-mysql-server/issues/392 and I noticed that the float64 results get truncated as integers.

I've also tested via another function AVG and that is also happening. For example:

Mysql-8
---
```
mysql> select avg(23.222);
+-------------+
| avg(23.222) |
+-------------+
|  23.2220000 |
+-------------+
1 row in set (0.01 sec)
```
go-mysql-server
---
```
mysql> select avg(23.222);
+-------------+
| AVG(23.222) |
+-------------+
|          23 |
+-------------+
1 row in set (0.00 sec)
```

Until that is solved some issues cannot go forward

**Comment by kuba--** [comment]
From mysql point of view everything looks fine. I think it's a gitbase issue.

**Comment by theodesp** [comment]
Cool I will continue with the  #392
