### ISSUE TITLE
Collect session warnings

### ISSUE THREAD

**Issue by kuba--** [src-d/go-mysql-server#465]
After we implemented `SHOW WARNINGS`, right now we need to collect to session warnings.
PR: https://github.com/src-d/go-mysql-server/pull/464 extended `Session` interface by:
- `AppendWarning(warn *sql.Warning)`
- `Warnings()[]*sql.Warning`
So, what left is to collect session warnings and call `ctx.Session.AppendWarning(...)`

Related to: 
- https://github.com/src-d/go-mysql-server/issues/442
- https://github.com/src-d/go-mysql-server/pull/464

- https://dev.mysql.com/doc/refman/8.0/en/show-warnings.html

**Comment by erizocosmico** [comment]
`AppendWarning` is perhaps too specific to how it's implemented. How about `AddWarning` or just `Warn`?
