### ISSUE TITLE
Please, add me as contributor #Hacktoberbest

### ISSUE THREAD

**Issue by Julineo** [src-d/go-mysql-server#485]
Please, add me ma as a new contributor. #Hacktoberbest

**Comment by ajnavarro** [comment]
Hey @Julineo ,

[Contributors list](https://github.com/src-d/go-mysql-server/graphs/contributors) is not made by hand, it is analyzing commits on the master branch and checking people that actually did some bug fixing or added some functionality.

The only way to be a contributor is creating a [pull request](https://github.com/src-d/go-mysql-server/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc) fixing some bug, or adding some new functionality. You can start from [here](https://github.com/src-d/go-mysql-server/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Ahacktoberfest).

Don't hesitate to ask if you have some dubt!

**Comment by Julineo** [comment]
I'm new to open sourcing. Still figuring out a GitHub workflow. Should I fork a repo and work on it, or clone the repo to local?

**Comment by erizocosmico** [comment]
@Julineo you can check out this article covering all the things you need to do to contribute on a github repository: https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/

**Comment by Julineo** [comment]
For some reason I can't add upstream repo: git remote add upstream https://github.com/src-d/go-mysql-server.git
