### ISSUE TITLE
[Tableau] - Support DEFAULT expression

### ISSUE THREAD

**Issue by kuba--** [src-d/go-mysql-server#487]
When Tableau starts, it sends multiple queries. One of them is:
```sql
set @@sql_select_limit=DEFAULT
```

So far we don't support `DEFAULT` keyword as an expression.

**Comment by bzz** [comment]
Shall this be closed as well?

> @ajnavarro ajnavarro moved this from To Deploy to Done in Data Retrieval 13 days ago

I tried on gibase v0.18.0-beta.2 and this query does not fail and return an empty result.
