### ISSUE TITLE
Disable or capture log from go-vitess

### ISSUE THREAD

**Issue by jfontan** [src-d/go-mysql-server#490]
Vitess uses `glog` for logging and it sometimes writes information in between our logging:

```
INFO[0000] server started and listening on 0.0.0.0:3333 
INFO[0011] NewConnection: client 1                      
ERROR: logging before flag.Parse: W1022 11:38:05.781017   13955 server.go:310] Error authenticating user using MySQL native password: Access denied for user 'mysql_user3' (errno 1045) (sqlstate 28000)
INFO[0011] ConnectionClosed: client 1    
```

We could disable these lines using environment variables for `glog` or even better change the logging facility to use ours. This probably requires changing the logging stub when importing code:

https://github.com/src-d/go-vitess/blob/v1.2.0/vt/log/log.go

**Comment by erizocosmico** [comment]
Didn't we have a script that replaced glog with logrus?

**Comment by jfontan** [comment]
Not anymore. I suppose we can take it back:

https://github.com/src-d/go-mysql-server/commit/031d7f72a1c85a4bae81627f7d2719815c5dc9a3#diff-6b0d443d17b4c508f1f4808ec1ea8391R43
