### ISSUE TITLE
this is a bug with go-vitess.v1 ? with roolback to go-vitess.v1:v1.0.0 ok when run _example/main.go

### ISSUE THREAD

**Issue by kSpacer201** [src-d/go-mysql-server#519]
- when I run `go run main.go with default version v1.1.0 in the go.md`
  it will break:
   ```
   gopkg.in\src-d\go-mysql-server.v0\server\server.go:57:60: cannot use handler (type *Handler) as type 
   mysql.Handler in argument to mysql.NewListener:
        *Handler does not implement mysql.Handler (missing WarningCount method)
   ```
- but rollback go-vitess.v1 to v1.0.0
  it is no breaking and runing...

**Comment by ajnavarro** [comment]
Hello @kSpacer201 !

We updated go-vitess to use the latest version. The error should be fixed on master by: https://github.com/src-d/go-mysql-server/pull/512

Thanks!

**Comment by kSpacer201** [comment]
@ajnavarro   Yes, v1.2.0 is ok. It seems that no v1.2.1 tag .... .

**Comment by ajnavarro** [comment]
Closing as fixed. If you have any other question, do not hesitate to do it.

**Comment by kSpacer201** [comment]
copy that
