### ISSUE TITLE
Substring function is not parsed correctly

### ISSUE THREAD

**Issue by theodesp** [src-d/go-mysql-server#532]
I'm trying to implement https://github.com/src-d/go-mysql-server/issues/483 but it looks like we broke substring. The unit tests run fine but when we login into a console it doesn't work.

```
mysql> select SUBSTRING("foo", 2, 2);
ERROR 1105 (HY000): unknown error: syntax error at position 23 near 'foo'
mysql> select substring("foobar", 1, 2);
ERROR 1105 (HY000): unknown error: syntax error at position 26 near 'foobar'
mysql> select SUBSTRING("foo", 1, 2);
ERROR 1105 (HY000): unknown error: syntax error at position 23 near 'foo'
```

**Comment by erizocosmico** [comment]
This is probably an issue with vitess, because afaik we don't parse substring manually.

**Comment by kuba--** [comment]
It will require fix in vitess. So far, we get from vitess:

```go
	// INVALID_ARGUMENT indicates client specified an invalid argument.
	// Note that this differs from FAILED_PRECONDITION. It indicates arguments
	// that are problematic regardless of the state of the system
	// (e.g., a malformed file name).
	Code_INVALID_ARGUMENT Code = 3
```

**Comment by kuba--** [comment]
Looks that vitess doesn't support `SubstrExpr` for static strings (only column names), so the fix is not super trivial just by updating vitess lexer but it will require changes in `ast` (by adding a new StaticSubstrExpr type or by extending current one SubstrExpr), then update lexer generator after that implement it in go-mysql-server parser.

**Comment by kuba--** [comment]
PR: https://github.com/vitessio/vitess/pull/4350
But it will also require changes in `/go-mysql-server.v0/sql/parse/parse.go` by adding to `func exprToExpression(e sqlparser.Expr)`:

```go
	case *sqlparser.SubstrExpr:
		var (
			name sql.Expression
			err  error
		)
		if v.Name != nil {
			name, err = exprToExpression(v.Name)
		} else {
			name, err = exprToExpression(v.StrVal)
		}
//...
```
