### ISSUE TITLE
Check correct usage of Null value

### ISSUE THREAD

**Issue by ajnavarro** [src-d/go-mysql-server#542]
Null type here: https://github.com/src-d/go-mysql-server/blob/master/sql/type.go#L152 shouldn't be a type in most of the cases. Null values always should have a type assigned. Null type should be used only when no other type is inferred, per example: `SELECT NULL` query.

**Comment by kuba--** [comment]
Can be related: https://github.com/src-d/go-mysql-server/issues/546
