### ISSUE TITLE
unsupported syntax: <nil>

### ISSUE THREAD

**Issue by campoy** [src-d/go-mysql-server#553]
Running this query fails on the latest release:

```sql
SELECT LANGUAGE(f.file_path, f.blob_content) AS lang, COUNT(*)  as n
FROM   files AS f
       JOIN commit_files
       JOIN refs
WHERE  ref_name = 'HEAD'
GROUP BY lang
```

I do not think this query is actually wrong, since simplifying it to this one makes it run successfully:

```sql
SELECT LANGUAGE(f.file_path, f.blob_content) AS lang, COUNT(*)  as n
FROM   files AS f
GROUP BY lang
```

The biggest problem right now is that the error message is this:

```
Query Failed - unknown error: unsupported syntax: <nil>
```

**Comment by kuba--** [comment]
Actually `ON` clause is missed for `JOIN` statement

**Comment by campoy** [comment]
This issue was closed, but when is the fix planned to be included in a gitbase release?

**Comment by ajnavarro** [comment]
@campoy Fix included here: https://github.com/src-d/gitbase/releases/tag/v0.18.0-beta.3
