### ISSUE TITLE
TPC-H: unsupported feature: HAVING

### ISSUE THREAD

**Issue by ajnavarro** [src-d/go-mysql-server#56]
Implement HAVING functionality: https://www.w3schools.com/sql/sql_having.asp

**Comment by mcarmonaa** [comment]
Stopped since this is not a priority in the OKRs

**Comment by andremarianiello** [comment]
Anyone have spare time to peek at this?

**Comment by erizocosmico** [comment]
@andremarianiello sure! Sorry for the delay, didn't see the PR.
