### ISSUE TITLE
[SQLAlchemy] ROLLBACK support or workaround

### ISSUE THREAD

**Issue by bzz** [src-d/go-mysql-server#563]
Following discussion from https://github.com/src-d/go-mysql-server/issues/319#issuecomment-441996211

SQLAlchemy sends `ROLLBACK` quite often:
   * [engine/default.py#initialize](https://github.com/zzzeek/sqlalchemy/blob/master/lib/sqlalchemy/engine/default.py#L285)
   * on recovery from any failure
   
This could possibly be worked around though [connection configuration options](https://github.com/zzzeek/sqlalchemy/blob/c99345ee9994c3ea2a5e6536cc3365f18d017cc1/doc/build/faq/connections.rst#why-does-sqlalchemy-issue-so-many-rollbacks), but a workaround is unknown.

Here is a [python snippet](https://gist.github.com/bzz/94c43cb22fa2bf69c09ccb4e47cfe781#python-code) to reproduce this.

**Comment by erizocosmico** [comment]
Perhaps `autocommit=False` might do the trick. Can you check using this? https://docs.sqlalchemy.org/en/latest/orm/session_transaction.html#autocommit-mode

**Comment by erizocosmico** [comment]
Pausing this until #587 and #588 are merged

**Comment by erizocosmico** [comment]
Just tried, can't be done via config. Pandas receives either Engine or Connection and both do a `ROLLBACK` during initialisation.

So that means we should implement `ROLLBACK`, even if it does nothing at the moment because there are no transactions. WDYT @ajnavarro?
