### ISSUE TITLE
yearweek function

### ISSUE THREAD

**Issue by erizocosmico** [src-d/go-mysql-server#616]
https://dev.mysql.com/doc/refman/5.5/en/date-and-time-functions.html#function_yearweek

**Comment by theodesp** [comment]
This is tricky as for example
```
mysql> SELECT YEARWEEK('1987-01-01');
        -> 198652
```

If we use the following ISOWeek method
https://play.golang.org/p/I6IbIHRqSaf

It will print 1987 for year and 1 for week. I don't know if its a bug or a featuer

**Comment by theodesp** [comment]
They also cover it with tests here
https://github.com/golang/go/blob/889aa5eb98ff2a5134f5b075525479da399e5c4f/src/time/time_test.go#L388
