### ISSUE TITLE
mysql.NewAuthServerStatic does not implement auth.Auth interface

### ISSUE THREAD

**Issue by dgrr** [src-d/go-mysql-server#622]
Hello,

The following code extracted from the README.md does not compile:
```go
    auth := mysql.NewAuthServerStatic()
    auth.Entries["user"] = []*mysql.AuthServerStaticEntry{{
        Password: "pass",
    }}

    config := server.Config{
        Protocol: "tcp",
        Address:  "localhost:3306",
        Auth:     auth,
    }
```

The error is produced because the function `gopkg.in/src-d/go-vitess.v1/mysql.NewAuthServerStatic()` does not implement `gopkg.in/src-d/go-mysql-server.v0/auth`.

Thanks.

**Comment by ajnavarro** [comment]
Thanks for the heads up, we will fix it ASAP.
