### ISSUE TITLE
Ignore SET keyword

### ISSUE THREAD

**Issue by jfontan** [src-d/go-mysql-server#63]
MySQL workbench executes `set` commands on start. These should be ignored:

```sql
set autocommit=1
SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ
```

**Comment by erizocosmico** [comment]
`SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ` is not even parseable by vitess.

This is the full list of queries executed by MySQL workbench.

```sql
set autocommit=1
SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ
SHOW SESSION VARIABLES LIKE 'lower_case_table_names'
SELECT current_user()
SET CHARACTER SET utf8
SET NAMES utf8
SHOW SESSION VARIABLES LIKE 'sql_mode'
SELECT CONNECTION_ID()
SHOW SESSION STATUS LIKE 'Ssl_cipher'
USE `db`
SHOW GLOBAL STATUS
```

Even after passing all those queries, the following error is shown by the app:

<img width="461" alt="screen shot 2018-03-08 at 14 39 04" src="https://user-images.githubusercontent.com/1312023/37153895-7b71777e-22de-11e8-9f4e-397489988dee.png">

I don't know if all this is worth the work it implies for the time being.

**Comment by jfontan** [comment]
It may not be worth for the first version. We may also want to test other clients, for example:

* [DbVisualizer](http://www.dbvis.com/)
* [DBeaver](https://dbeaver.jkiss.org/)
* [sqlectron](https://github.com/sqlectron/sqlectron-gui)

**Comment by smola** [comment]
Ignoring the SET keyword altogether might not be desirable, since the client might be expecting that those SET have a particular behaviour. Maybe this issue should be changed to just look into what we can do to make it compatible with MySQL Workbench?

**Comment by erizocosmico** [comment]
@smola yep. `SET` is implemented in #129, but vitess does not support the syntax of all the SET commands workbench sends.

Here's https://github.com/src-d/go-mysql-server/issues/63#issuecomment-371488997 the full list of commands we need to support for that

**Comment by mcuadros** [comment]
We don;t need to support workbench or any other admin tool, the request of ignoring the `SET` was a quick solution to make it work, but if it requires any mid/big work, we are not going to do oit.

**Comment by ajnavarro** [comment]
Closing this as is not needed to ignore `set` anymore, it is already implemented.
