### ISSUE TITLE
Index generation is slower than previous implementation

### ISSUE THREAD

**Issue by ajnavarro** [src-d/go-mysql-server#676]
Log indexing a table with the actual version:

```
DEBU[0461] finished pilosa indexing                      duration=5m26.700323786s id=blobs_idx mapping=508129748 pilosa=384190894 rows=55764
```

Log with previous implementation, the same table:
```
DEBU[0022] finished pilosa indexing                      duration=5.323093051s id=blobs_idx mapping=429.571981ms pilosa=268.452932ms rows=55796
```

5 mins vs 5 secs.

**Comment by kuba--** [comment]
<img width="382" alt="Screen Shot 2019-04-16 at 14 39 50" src="https://user-images.githubusercontent.com/4056521/56210212-99c7b700-6055-11e9-9ef5-b515d7dcfbd1.png">

**Comment by kuba--** [comment]
After creating mapping per partition we get better performance:
<img width="152" alt="Screen Shot 2019-04-16 at 19 19 14" src="https://user-images.githubusercontent.com/4056521/56230495-aad7ee80-607c-11e9-8e37-0176b1997230.png">

**Comment by kuba--** [comment]
you can see that `bbolt.Commit` dropped from 3.39s to 0.06s

**Comment by kuba--** [comment]
The fix will break backward compatibility, because we'll require mapping file per partition.

**Comment by erizocosmico** [comment]
It's a 0.x, so I guess it's fine to break compat
