### ISSUE TITLE
Nested SUBSTRING fails with INVALID_ARGUMENT error

### ISSUE THREAD

**Issue by smola** [src-d/go-mysql-server#705]
This works, both with positive and negative indexes:
```
SELECT
    repository_id,
    remote_fetch_url,
    SUBSTRING(remote_fetch_url, 18)
FROM remotes;
```

```
SELECT
    repository_id,
    remote_fetch_url,
    SUBSTRING(SUBSTRING(remote_fetch_url, 18), -4)
FROM remotes;
```

But this fails from gitbase-web with error:

```
Query Failed - unknown error: Code: INVALID_ARGUMENT syntax error at position 69 near 'substring' 
``` 

Running gitbase-0.20.0-rc1

**Comment by kuba--** [comment]
First we need to merge the fix in vitess: https://github.com/vitessio/vitess/pull/4867

**Comment by smola** [comment]
Just for reference, doing a second SUBSTRING in a subquery serves as a workaround. For example:
```sql
SELECT SUBSTRING(repository_id, 1, ARRAY_LENGTH(SPLIT(repository_id, ''))-4) AS b
FROM (
SELECT SUBSTRING(remote_fetch_url, 18) AS repository_id
FROM remotes
) AS q
```

**Comment by kuba--** [comment]
Yep, this is clear. The problem is SQL grammar - `SUBSTRING` expects static string or column name, so `SUBSTRING(REPLACE(...)...)` should not also work.
