### ISSUE TITLE
Add FIRST/LAST aggregations

### ISSUE THREAD

**Issue by smola** [src-d/go-mysql-server#718]
* Let's consider adding FIRST/LAST aggregations.
* Present in Spark SQL, not sure if in MySQL.
* In gitbase, these are useful, for example, to get all blobs with _any_ of their associated file names. In our case, running in gitbase-spark-connector without push down may be fine (I'm playing with that now).

**Comment by juanjux** [comment]
There doesn't seem to be implementation of these in MySQL but there are the window functions `FIRST_VALUE` and `LAST_VALUE`. Would be nice to have them in go-mysql-server anyway.

**Comment by erizocosmico** [comment]
FIRST_VALUE and LAST_VALUE require windows, which we don't have and is significantly more complex.
