### ISSUE TITLE
gitbase dies for query with WHERE NOT <not boolean value>

### ISSUE THREAD

**Issue by zurk** [src-d/go-mysql-server#726]
If you try to query something like: 
```
select repository_id, commit_author_when, commit_parents from commits WHERE NOT commit_parents
```
gitbase dies. It is not a valid SQL query, because `commit_parents` type is not boolean, but I expect that `gitbase` remains available for new queries.

It is useful to have some general check if gitbase fails to process the query and do not shut down if the query was bad.

**Comment by smola** [comment]
I think it's ok to just check for bool on evaluation if you introduce the right `CAST` during analysis.
