### ISSUE TITLE
LEFT JOIN and RIGHT JOIN are returning more than a single row per left/right row

### ISSUE THREAD

**Issue by erizocosmico** [src-d/go-mysql-server#742]
https://github.com/src-d/gitbase/issues/852

**Comment by zurk** [comment]
@src-d/data-processing can I ask you to make a new release with a fix and new release of gitbase?

**Comment by erizocosmico** [comment]
It's waiting for this to be merged before we can update: https://github.com/src-d/gitbase/pull/847
