### ISSUE TITLE
How do I make this join more efficient?

### ISSUE THREAD

**Issue by andremarianiello** [src-d/go-mysql-server#751]
If I have two tables, `a` and `b`, and I want to get the results of the following query:

```
SELECT * FROM a JOIN b on a.id = b.id where a.name = 'foo';
```

I know, based on the datasources that I'm using, that the best way to run this query is to get all rows from `a` where `a.name = 'foo'`, and then for each id in those rows, query `b` asking for the rows with that id. A full table scan on `b` would be way too slow, but `b` can push down filters to get the rows based on `id` much more efficiently. What can I do to avoid the full table scan on `b`? My light amount of testing and brief look at the code makes it seem to me like a join will always require a full scan of both tables, at minimum.

**Comment by erizocosmico** [comment]
Hi, there is no way to avoid full table scan on `b`. A join is implemented basically as a cross join with a filter, which requires full scan of both tables.
In any case, even if pushing down the `id` as filter was possible, it would require an index on that table.

**Comment by andremarianiello** [comment]
> even if pushing down the id as filter was possible, it would require an index on that table

Could you elaborate on this a little more? I thought that tables that implemented the FilteredTable interface could pushdown predicates.

**Comment by ajnavarro** [comment]
Hey @andremarianiello 

We can pushdown filters that are using literals to filter as much as possible the source of data.

Per example, on your example query, `a.name = 'foo'` can be pushed down to table `a`, but `a.id = b.id` cannot be pushed down because it doesn't contain a literal.

**Comment by zachmu** [comment]
Are there any current plans to make joins more efficient for this common case (join N tables on indexed columns)? I'm willing to contribute if there's consensus that this is important.

**Comment by ajnavarro** [comment]
Hey @zachmu,

Right now there are no plans to make joins more efficient in that case, but if you have a proposal of how to implement it, we can have a look into it and try to make it possible with your help.

Thanks!

**Comment by erizocosmico** [comment]
Closing, as the question has been resolved.
