### ISSUE TITLE
Add `sql/expression/literal_test.go`

### ISSUE THREAD

**Issue by juanjux** [src-d/go-mysql-server#776]
Just noticed that the module is missing the test module.

**Comment by erizocosmico** [comment]
Do you mean that file is missing?

**Comment by juanjux** [comment]
Yes, should have an specific test module for the stuff there, I guess.

**Comment by erizocosmico** [comment]
Not really, it just returns the literal kept in the struct. I don't think it's worth testing.

**Comment by juanjux** [comment]
Fair enough, I'll add a test later if I see how I can evaluate the VarChar length and return an error in NewLiteral.
