### ISSUE TITLE
Connection timeouts can't be processed if a query is running.

### ISSUE THREAD

**Issue by juanjux** [src-d/go-mysql-server#799]
Connection timeouts from Vitess doesn't trigger, and thus stop the query, is a query is running but not sending anything. This is because query processing and the `Handler` run on the same thread, so when Vitess detects a timeout the call to `CloseConnection` can't be processed until the query finishes.

Related to: https://github.com/src-d/gitbase-spark-connector-enterprise/issues/81

**Comment by erizocosmico** [comment]
Fix to this was already merged at https://github.com/src-d/go-mysql-server/pull/801
