### ISSUE TITLE
question: how to implement index

### ISSUE THREAD

**Issue by xrfang** [src-d/go-mysql-server#803]
Hi there,

I try to write a sql-server frontend to my data stored in boltdb.  Following Justforfunc's CSVQL demo, I have successfully added partitioning support to CSVQL, but when I try to add index capabilities. I am stucked.  The relationships between all these interfaces seems very cryptic, and there is no  documents.

For example, I don't know how to implement the Next() method of sql.IndexKeyValueIter interface.  In the source code:

```
// IndexKeyValueIter is an iterator of index key values, that is, a tuple of
// the values that will be index keys.
type IndexKeyValueIter interface {
	// Next returns the next tuple of index key values. The length of the
	// returned slice will be the same as the number of columns used to
	// create this iterator. The second returned parameter is a repo's location.
	Next() ([]interface{}, []byte, error)
	io.Closer
}
```
What is "a tuple of the values that will be index keys"?  And why is the first return value a slice of interface{}, how is it used by the caller?

Could you please add some example, just using CSVQL, of implementing IndexableTable?  Or, is there any overiew document on how all the index related interfaces interact with each other?

Thanks a lot!

**Comment by ajnavarro** [comment]
Hello @xrfang ,

Here you have an example of index implementation: https://github.com/src-d/gitbase/blob/master/commits.go#L151

`IndexKeyValueIter` is intended to be used internally to create the index itself, using key-value format, and stored by partitions to make possible use the index on multi-thread mode if needed.

`Next() ([]interface{}, []byte, error)``is intended to return normalized data from the table implementation that will be used to generate the index. Per example, if we have the following table:

| a | b  | c   |
|---|----|-----|
| 1 | 10 | 100 |
| 2 | 20 | 200 |
| 3 | 30 | 300 |

If we want to create an index for `a` column, Next() will return (assuming that the partition location is just one: `[]byte{'1'}`):
- `([]interface{int64(1)}, []byte{'1'})`
- `([]interface{int64(2)}, []byte{'1'})`
- `([]interface{int64(3)}, []byte{'1'})`

If we want to index a specific expression, per example `concat(a,b)` we will return:
- `([]interface{int64(1), int64(10)}, []byte{'1'})`
- `([]interface{int64(2), int64(20)}, []byte{'1'})`
- `([]interface{int64(3), int64(30)}, []byte{'1'})`

**Comment by xrfang** [comment]
Thanks  @ajnavarro   my understanding is that the index is doing exact one thing: tell the engine in which **partition** a specific data could be found, right ?   Does this mean that uniqueness is not considered in the go-mysql-server engine ?  e.g.  to index column `a`:

a | b | c
-- | -- | --
1 | 10 | 100
1 | 20 | 200

Next() will return:

* ([]interface{int64(1)}, []byte{'1'})
* ([]interface{int64(1)}, []byte{'1'})

right ?

**Comment by ajnavarro** [comment]
@xrfang exactly.

**Comment by erizocosmico** [comment]
Closing, as the question has been resolved.
