### ISSUE TITLE
question: how to use catalog.SetCurrentDatabase()

### ISSUE THREAD

**Issue by xrfang** [src-d/go-mysql-server#805]
I tried to issue the USE command in mysql client and found that the current database is NOT switched as requested.  Also, this message is emited on server console:

```
ERRO[0046] Got unhandled packet (default) from client 1 (127.0.0.1:60914), returning error: [4 117 115 101 114 115 0] 
```

By searching the code, I found there is catalog.SetCurrentDatabase() which is supposed to switch the db in use. But it seems not called?

All the interfaces required to be implemented are done so (otherwise it won't compile anyway).   

How can I ask the engine to switch current db?   Or in general, how is a sql command handled, e.g. if I issue an UNKNOWN_COMMAND is there a fallback handler that could be used to implement the code for that command?

Thanks!

**Comment by ajnavarro** [comment]
Hello!

`USE` command is actually implemented. If the database name is not found, some strange errors appear from the server console. Appears that `resolveDatabase` rule is not correctly implemented to handle database switch. We will have a look at it.

Commands should be implemented here: https://github.com/src-d/go-mysql-server/blob/master/sql/parse/parse.go 

If the new command is not supported by Vitess sql parser, you must add the query parser too.

**Comment by ajnavarro** [comment]
Regarding error on USE command here we have some tests: https://github.com/src-d/go-mysql-server/blob/master/engine_test.go#L2657-L2672

I was not able to reproduce that error on the latest version.
