### ISSUE TITLE
resolveDatabase is not working if database is changed using USE

### ISSUE THREAD

**Issue by ajnavarro** [src-d/go-mysql-server#810]
related: https://github.com/src-d/go-mysql-server/issues/805

We need to handle database change on `resolveDatabase` rule. Right now is only resolving the current database.

**Comment by erizocosmico** [comment]
Can you provide a reproduction case for this? As far as I can see this behaviour is tested and working properly: https://github.com/src-d/go-mysql-server/blob/master/engine_test.go#L2657-L2672

**Comment by ajnavarro** [comment]
I did some tests and I'm not able to reproduce the error anymore.
