### ISSUE TITLE
ORDER BY does not fail on non-existent columns

### ISSUE THREAD

**Issue by Hydrocharged** [src-d/go-mysql-server#813]
`ORDER BY` does not throw an error if a non-existent column is supplied. One would expect similar behavior to supplying a non-existent column to `GROUP BY`, which results in the following error:

```go
ErrColumnNotFound = errors.NewKind("column %q could not be found in any table in scope")
```

Attached is a patch that may be applied to the [latest as of the time of this issue filing](https://github.com/src-d/go-mysql-server/tree/1783e9035bce6432f73a877ea42e8b467578e57f). This adds a few lines to the `TestOrderByGroupBy` test that checks for an error to be returned when a non-existent column is supplied.

[patch.txt](https://github.com/src-d/go-mysql-server/files/3580850/patch.txt)

**Comment by erizocosmico** [comment]
Thank you for reporting this issue, we'll take a look as soon as we can.
