### ISSUE TITLE
LIKE fails when new lines are present

### ISSUE THREAD

**Issue by Hydrocharged** [src-d/go-mysql-server#814]
`LIKE` does not search a string when it contains a new line anywhere in the string. It does not error, but does not return the line even though the text is contained within, when the expected behavior is to return all rows that match.

Attached is a patch that may be applied to the [latest as of the time of this issue filing](https://github.com/src-d/go-mysql-server/tree/1783e9035bce6432f73a877ea42e8b467578e57f). This adds a new `SELECT` test for the `LIKE` issue, along with a new memory table, and changes the relevant tests to also look for the new table.

[patch.txt](https://github.com/src-d/go-mysql-server/files/3581007/patch.txt)

**Comment by erizocosmico** [comment]
Thank you for reporting this issue, we'll take a look as soon as we can.

**Comment by agarciamontoro** [comment]
Thank you for the catch, @Hydrocharged! Could you open a PR with the tests that you provided? The fix for them is already in https://github.com/src-d/go-mysql-server/pull/817.

**Comment by agarciamontoro** [comment]
The fix is already merged, but the tests no. I'm reopening this so we can track the tests from @Hydrocharged.

**Comment by agarciamontoro** [comment]
Tests merged in #820.
