### ISSUE TITLE
Returned types do not fit the schema

### ISSUE THREAD

**Issue by agarciamontoro** [src-d/go-mysql-server#834]
All integer types (except for `uint64`) are converted to `int64`, regardless of what was defined in the original schema of the table. This creates an overhead in space that should not be there. It also creates weird casting bugs in very particular scenarios (e.g., gitbase connected to Spark).

## Example

The `typestable` table created in [`engine_test.go#L2674-L2691`](https://github.com/src-d/go-mysql-server/blob/b09e8c1c8a/engine_test.go#L2674-L2691) has columns of each and every type of signed and unsigned integers.

However, as soon as we make an INSERT into it and try to SELECT all the columns from it, as shown [in one of the tests](https://github.com/src-d/go-mysql-server/blob/b09e8c1c8a/engine_test.go#L1858-L1873), the integer data types are all converted to `int64`, regardless of what they were originally (`uint8`, `int16`, `uint32`...). The only exception is `uint64`, whose maximum is of course greater than the maximum of `int64`.

Actually, these tests are wrong as well, as the returned value should not always be converted to `int64` but to the type specified in the schema.

#### Parse the literals as the smallest integer possible

The integer literals are always parsed as `int64`, defaulting to `uint64` if the first parsing fails. See [sql/parse/parse.go#L945-L956](https://github.com/src-d/go-mysql-server/blob/b09e8c1c8a/sql/parse/parse.go#L945-L956).

As the `TODO` comment there, I propose to parse the literal to the smallest integer possible, defaulting to greater integers if necessary, as follows:
```
int8 < uint8 < int16 < uint16 < int32 < uint32 < int64 < uint64
```
An example of such a change is in [my fork](https://github.com/agarciamontoro/go-mysql-server/commit/922906c52673766e435b764e93d558c5b93e6ed2), although it was a test that considered only `int32`, so it should be expanded to all the other types.

#### Convert to greater types when necessary

The smallest integer possible for a parsed literal my not be the expected type for it, so we should convert them back to greater types when needed. 

For example, when doing the INSERT queries, a literal may be parsed as an `int8` when the column type is `int64`. The conversion will be safe as the parsed number will always be smaller or equal than the maximum accepted by the type (assuming the query is correct; the user can write a number greater than the maximum allowed by the column, but failing there is the correct thing to do).

For this case of the INSERT, I propose to implement a new rule in the plan that converts the parsed literals into the right type specified by the column.

This would probably be a big change, as there are some hard-coded literals with specific types that will fail after applying the previous solution (there are [some](https://github.com/agarciamontoro/go-mysql-server/commit/d2e6f4b6f109a4cf62fda2bef65fe75933287dcf) [examples](https://github.com/agarciamontoro/go-mysql-server/commit/93a8634fcc653ca77e78d58a2e5b930e557de164) [in](https://github.com/agarciamontoro/go-mysql-server/commit/d239aa4d9eb363016a8cedac2ac2b74d55761ba6) [my](https://github.com/agarciamontoro/go-mysql-server/commit/29a2f812d346bcc62f0e041f6546ef0f8c24b160) [branch](https://github.com/agarciamontoro/go-mysql-server/commit/02087f4417e9e6aa0819e699d584ce14b053e9a3)). Fortunately, the test suite is quite comprehensive and covers most corner cases

**Note**: as this is probably a big change, as described before, I would like to discuss the details with @src-d/data-processing before going down that road. What do you think?

**Comment by erizocosmico** [comment]
I think we only have Int32 and Int64 defined in gitbase. Using only those would be fine, no need to go down to int8, int16 and so on.

**Comment by agarciamontoro** [comment]
That would probably fix it for gitbase, but I still think that not covering the other cases is wrong, as someone could define a column of type `TINYINT` (1 byte) and we still would be parsing literals that fit there as a 4 bytes integer.
