### ISSUE TITLE
Archive src-d/go-mysql-server in favor of liquidata-inc/go-mysql-server

### ISSUE THREAD

**Issue by zachmu** [src-d/go-mysql-server#873]
Hello src-d,

We have been developing our fork of this project for about six months since the last update. It now includes hundreds of commits that fix bugs, add features, and improve test coverage.

https://github.com/liquidata-inc/go-mysql-server/

As this project appears to be defunct, please archive it and promote our fork as the new "master" fork, similar to what was done with https://github.com/go-git/go-git. We plan to continue development of this project as open source indefinitely.

**Comment by erizocosmico** [comment]
Hi!

Not sure if it can be done due to legal reasons. go-git was hard-forked instead of transferred. 

I’m tagging here two people who may be able to help you with this

/cc @eiso @marnovo

**Comment by zachmu** [comment]
Thanks, any help would be appreciated.

A hard fork would be fine if that's our best option (I believe that our fork is the only active one). In that case, a notice on the archived project informing collaborators of the move would be great.

**Comment by ajnavarro** [comment]
Sorry to not be able to transfer the project, really appreciate the work that you are doing maintaining it.

Maybe @mcuadros can help here too adding some message pointing to your fork and archiving this repository.

**Comment by mcuadros** [comment]
@zachmu I believe that for the community, in general, will be better if you hardfork the project into a new org called `go-mysql-server`, to avoid similar problems in the future.

My company @gitsight is maintaining go-git but instead of creating the fork there, it was created on `go-git` org.

**Comment by zachmu** [comment]
@mcuadros We discussed this on the team, and have decided to keep our fork in the liquidata-inc org for the time being. It's a critical piece of our own open source project offering, and its roadmap will be tightly coupled to that project's needs for the foreseeable future. But we will certainly take care to be good stewards of the project and transfer ownership in the unlikely event we can't continue as a company.

Again, appreciate the work you all did on this great engine. Your issues, PRs and guidance will be very welcome if you submit them.

**Comment by s7v7nislands** [comment]
now https://github.com/dolthub/go-mysql-server ?

**Comment by zachmu** [comment]
@s7v7nislands Yes, correct.
