### ISSUE TITLE
Panic comparing literals and columns numbers

### ISSUE THREAD

**Issue by ajnavarro** [src-d/go-mysql-server#92]
If we have the following query:
`SELECT a from b where a > 10`
It will panic because `a` is an int32 and the literal `10` is an int64 by default. Line on parse.go:
```go
return expression.NewLiteral(n, sql.Int64), nil
```

The standard solution for this is add a `CAST` node surrounding the literal, casting it to the type of the other expression into the comparison. Doing this, all the those queries will be executable:
`SELECT a from b where a > 10`
`SELECT a from b where a > "10"`
`SELECT a from b where a > 10.0`
`SELECT a from b where 10 < a`

**Comment by erizocosmico** [comment]
Or in `Comparison.Compare` we could do a `Left.Type().Convert(right)` and use that one to compare

**Comment by ajnavarro** [comment]
But how do you know that you should call `left.Type().Convert(right)` instead of `right.Type().Convert(left)`

**Comment by erizocosmico** [comment]
Yep, you're right.
