### ISSUE TITLE
Improve error messages

### ISSUE THREAD

**Issue by ajnavarro** [src-d/go-mysql-server#93]
Right now, if some query failed on resolution process, an error like this is obtained:

```
    Error:          Received unexpected error:
                        2 errors occurred:
                        
                        * plan is not resolved because of node '*plan.Project'
                        * plan is not resolved because of node '*plan.Filter'
```

Improve error messages to add more information about what is failing on that nodes.

**Comment by ajnavarro** [comment]
I think it depends on #95

**Comment by erizocosmico** [comment]
Can you provide an example of a query that produces this error? @ajnavarro

**Comment by ajnavarro** [comment]
Maybe now with all the changes since 8 days ago is difficult to reproduce it. I got it adding a column name on the project that is not on the table.

**Comment by ajnavarro** [comment]
I was able to reproduce the main error executing this: `describe tables;`

**Comment by erizocosmico** [comment]
Can't reproduce with `describe tables` either. It returns an unsupported syntax error instead.

El mié., 21 mar. 2018 a las 18:16, Antonio Navarro Perez (<notifications@github.com<mailto:notifications@github.com>>) escribió:

I was able to reproduce the main error executing this: describe tables;
